import type { NextPage } from 'next'
import Head from 'next/head'
import { useState, useEffect } from 'react'
import Post from '../components/Posts/Post'
import Script from 'next/script'
import axios from 'axios'
import SkullPost from '../components/Posts/SkullPost'


const Home: NextPage = () => {
  const [darkMode, setDarkMode] = useState<boolean>(false)
  const [posts, setPosts] = useState<any>()

  useEffect(() => {
    themeCheck()
  })

  const themeCheck = () => {
    if(localStorage.theme === 'dark' || (!('theme' in localStorage) && window.matchMedia("(prefers-color-scheme: dark)").matches)) {
      setDarkMode(true)
    } else{
      setDarkMode(false)
    }
  }


  useEffect(() => {
    const fetchPosts = async () => {
      const response = await axios.get('/api/posts/get_posts')
      const data = await response.data
      
      setPosts(data.posts)
      
    }
      fetchPosts()
  })

  return (
    <div className={` w-screen  md:h-auto md:w-full flex justify-center items-center`}>
      <Head>
        <title>MUIDS | Homeroom Hub</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Script src="https://cdn.jsdelivr.net/npm/swiper@9/swiper-element-bundle.min.js"></Script>
      <div className='flex flex-col justify-center items-center w-full md:mt-0 md:py-0 md:my-10 space-y-5'>
        
        { posts && posts.map((_n: any, i: string | number) => {
          return (
            <Post key={posts[i]._id} _id={posts[i]._id} profile_pic={posts[i].profile_pic} author={posts[i].author} post_pic={posts[i].post_pic} like={posts[i].like} time={posts[i].time} title={posts[i].title} description={posts[i].description}></Post>
            )
        })}        

        { !posts && 
          <>
            <SkullPost></SkullPost>
            <SkullPost></SkullPost>
            <SkullPost></SkullPost>
          </>
        }

      </div>
      
    </div>
  )
}

export default Home


